spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.h2.console.enabled=false
spring.flyway.enabled=true

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-ms=3600000
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}
app.security.h2-console-enabled=false
app.bootstrap-admin.username=${APP_BOOTSTRAP_ADMIN_USERNAME}
app.bootstrap-admin.password=${APP_BOOTSTRAP_ADMIN_PASSWORD}
